set(BUILD_SHARED_LIBS_ORIG ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS OFF CACHE INTERNAL "")

set(WEBP_BUILD_ANIM_UTILS OFF CACHE BOOL "")
set(WEBP_BUILD_CWEBP OFF CACHE BOOL "")
set(WEBP_BUILD_DWEBP OFF CACHE BOOL "")
set(WEBP_BUILD_GIF2WEBP OFF CACHE BOOL "")
set(WEBP_BUILD_IMG2WEBP OFF CACHE BOOL "")
set(WEBP_BUILD_VWEBP OFF CACHE BOOL "")
set(WEBP_BUILD_WEBPINFO OFF CACHE BOOL "")
set(WEBP_BUILD_LIBWEBPMUX OFF CACHE BOOL "")
set(WEBP_BUILD_WEBPMUX OFF CACHE BOOL "")
set(WEBP_BUILD_EXTRAS OFF CACHE BOOL "")

set(LIBSHARPYUV_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/ext/libwebp")
if(ANDROID_ABI)
    set(LIBSHARPYUV_BINARY_DIR "${LIBSHARPYUV_BINARY_DIR}/${ANDROID_ABI}")
endif()
FetchContent_Declare(
    libwebp
    GIT_REPOSITORY "https://chromium.googlesource.com/webm/libwebp"
    SOURCE_DIR "${AVIF_SOURCE_DIR}/ext/libwebp" BINARY_DIR "${LIBSHARPYUV_BINARY_DIR}"
    GIT_TAG "v1.3.2"
    GIT_SHALLOW ON
    UPDATE_COMMAND ""
)

if(NOT libwebp_POPULATED)
    FetchContent_Populate(libwebp)
    add_subdirectory(${libwebp_SOURCE_DIR} ${libwebp_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()

add_library(libsharpyuv::libsharpyuv ALIAS sharpyuv)

set(BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS_ORIG} CACHE BOOL "" FORCE)

set_property(TARGET sharpyuv PROPERTY POSITION_INDEPENDENT_CODE ON)
set_property(TARGET sharpyuv PROPERTY AVIF_LOCAL ON)

set(LIBSHARPYUV_INCLUDE_DIR ${AVIF_SOURCE_DIR}/ext/libwebp)
target_include_directories(
    sharpyuv INTERFACE $<BUILD_INTERFACE:${LIBSHARPYUV_INCLUDE_DIR}> $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDE_DIR}>
)
set(libsharpyuv_FOUND ON CACHE BOOL "")
set(LIBSHARPYUV_LIBRARY sharpyuv)
