set(AVIF_LOCAL_LIBXML_GIT_TAG "v2.11.5")

set(LIBXML2_WITH_PYTHON OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_ZLIB OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_LZMA OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_ICONV OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_TESTS OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_PROGRAMS OFF CACHE INTERNAL "-")
set(LIBXML2_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/ext/libxml2")
if(ANDROID_ABI)
    set(LIBXML2_BINARY_DIR "${LIBXML2_BINARY_DIR}/${ANDROID_ABI}")
endif()

FetchContent_Declare(
    libxml2
    GIT_REPOSITORY "https://gitlab.gnome.org/GNOME/libxml2.git"
    SOURCE_DIR "${AVIF_SOURCE_DIR}/ext/libxml2" BINARY_DIR "${LIBXML2_BINARY_DIR}"
    GIT_TAG "${AVIF_LOCAL_LIBXML_GIT_TAG}"
    GIT_SHALLOW ON
    UPDATE_COMMAND ""
)

avif_fetchcontent_populate_cmake(libxml2)

set_property(TARGET LibXml2 PROPERTY AVIF_LOCAL ON)

set(LIBXML2_LIBRARY LibXml2::LibXml2)
set(LIBXML2_FOUND ON)
