set(BUILD_SHARED_LIBS_ORIG ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_PYTHON OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_ZLIB OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_LZMA OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_ICONV OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_TESTS OFF CACHE INTERNAL "-")
set(LIBXML2_WITH_PROGRAMS OFF CACHE INTERNAL "-")
set(LIBXML2_BINARY_DIR "${CMAKE_CURRENT_BINARY_DIR}/ext/libxml2")
if(ANDROID_ABI)
    set(LIBXML2_BINARY_DIR "${LIBXML2_BINARY_DIR}/${ANDROID_ABI}")
endif()
FetchContent_Declare(
    libxml2
    GIT_REPOSITORY "https://gitlab.gnome.org/GNOME/libxml2.git"
    SOURCE_DIR "${AVIF_SOURCE_DIR}/ext/libxml2" BINARY_DIR "${LIBXML2_BINARY_DIR}"
    GIT_TAG "v2.11.5"
    GIT_SHALLOW ON
    UPDATE_COMMAND ""
)

if(NOT libxml2_POPULATED)
    FetchContent_Populate(libxml2)
    add_subdirectory(${libxml2_SOURCE_DIR} ${libxml2_BINARY_DIR} EXCLUDE_FROM_ALL)
endif()

set_property(TARGET LibXml2 PROPERTY AVIF_LOCAL ON)

set(BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS_ORIG} CACHE BOOL "-" FORCE)
get_target_property(LIBXML2_INCLUDE_DIR LibXml2::LibXml2 INTERFACE_INCLUDE_DIRECTORIES)
set(LIBXML2_LIBRARY LibXml2::LibXml2)
set(LIBXML2_FOUND ON)
